#!/usr/bin/make
#
# handmade-hero				March 11, 2026
#
# source: src/linux/Makefile
# author: @misael-diaz
#
# Synopsis:
# Defines the Makefile for building the program with GNU make.
#
# Copyright (c) 2025 Misael Diaz-Maldonado
#
# This file is released under the MIT License.
#

all:

clean:
	echo "Windows"
